source 'https://github.com/xiaobt/FFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'FFAuthorKit_Category_Example' do
  pod 'FFAuthorKit_Category', :path => '../'

  target 'FFAuthorKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
